### ISSUE TITLE
Problema al cargar información financiera de un cliente con permisos de manager

### ISSUE THREAD

**Issue by lujambiodanilo** [ProyectoAconcagua/base_vat_ar_v7#1]
Se da de alta un usuario con el siguiente perfil

![seleccin_006](https://cloud.githubusercontent.com/assets/4148282/3167438/6408d8bc-eb6e-11e3-98b3-8526c772b475.png)

con ese usuario se da de alta un cliente OK . Pero al intentar grabarle a ese cliente información financiera , se produce un error de permisos.
La última línea del error contiene (Modelo de documento: res.document.type) 
Así se intentó llenar los campos del cliente:

![seleccin_007](https://cloud.githubusercontent.com/assets/4148282/3167463/d5177bb2-eb6e-11e3-8b03-baa6c705b107.png)

**Comment by kloss17** [comment]
Gracias Danilo, por el momento deberías asignar los permisos manualmente a ese objeto, estamos trabajando para que durante la instalación se automatice este proceso.

**Comment by gabrielcz** [comment]
Hola, me pasa igual... el tema, es que no sabia como dar los permisos manualmente para este objeto.
Alguien me intenta echar un cable?

Saludos,

**Comment by lbaldi** [comment]
Para dar permisos a ese objeto tendrías que hacer lo siguiente
Configuracion -> Seguridad -> Lista de controles de acceso -> Crear

Nombre : a gusto
Objeto: res.document.type
Grupo: Grupo al que le quieras aplicar la regla. Vacio en caso de que sea general
Lectura / Escritura / Creacion / Eliminar : a gusto

Tenes que jugar con el grupo y demas opciones para darle a ciertas personas mas o menos accesos

Para hacerlo bien tendrias que generar mas de una regla aplicadas a diferentes grupos.

Saludos!

**Comment by sebastiken** [comment]
@gabrielcz disculpá que no contesté antes. La explicación de @lbaldi es correcta. Igualmente, pido disculpas porque ese tema lo tenía solucionado en mi repo local desde noviembre del año pasado y olvidé subir los cambios a github. Están en el commit 58ce7508dbaeec08e932c4c0088bce9c76edaed7 que acabo de pushear.
Te pido que para que te agrega las **ACL** sincronices el módulo para tener este último _commit_ y luego actualices el módulo desde **OpenERP**.

Saludos.
